# config.py
GRID_SIZE = 8
CELL_SIZE = 58

WINDOW_WIDTH = 900
WINDOW_HEIGHT = 700

BG_COLOR = "#e8e8e8"
GRID_BG = "#ffffff"
CELL_COLOR = "#ffffff"

SELECTED_COLOR = "#a0d8ff"
CORRECT_COLOR = "#90ee90"
WRONG_COLOR = "#ff9999"
